spring:
  application:
    name: cinema_web
  config:
    import: config-server :http://localhost:8088
  cloud:
    config:
      enabled: true

#      uri: http://localhost:8088
#  profiles:
#    active: test
server:
  port: 8081